# How to use :
# caddy_user=admin caddy_pass=123456 docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:
  nginx:
    hostname: NGINX
    container_name: docker_nginx
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    networks: 
      vpn:
        ipv4_address: 172.168.21.2
    restart: on-failure


  torrent:
    hostname: TORRENT
    container_name: docker_torrent
    build: 
      context: ./torrent
      dockerfile: ./Dockerfile
    volumes:
      - ./downloads/:/downloads/
    ports:
      - "8080:8080"
      - "9000:9000"
      - "8081:8081"
      - "8081:8081/udp"
    networks: 
      vpn:
        ipv4_address: 172.168.21.3
    depends_on: 
      - nginx
    restart: on-failure


  caddy:
    hostname: CADDY
    container_name: docker_caddy
    build: 
      context: ./caddy
      dockerfile: ./Dockerfile
      args:
        - caddy_user=${CADDY_USER}
        - caddy_pass=${CADDY_PASS}
    volumes:
      - ./caddy/Caddyfile:/usr/local/caddy/Caddyfile
      - ./downloads/:/downloads/
    ports:
      - "9090:9090"
    networks: 
      vpn:
        ipv4_address: 172.168.21.4
    depends_on: 
      - torrent
    restart: on-failure


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.21.0/24
          gateway: 172.168.21.1
    